//! The generated `.d.ts`: a module augmentation of `@surrealguard/client` that
//! adds one `SurqlRegistry` entry per analyzed query, keyed by its exact text.
//!
//! A string-literal query passed to `SurrealGuardClient.query` resolves its
//! result and parameter types from these entries; TypeScript can key on the
//! literal because it infers literal types for string arguments (but never for
//! tagged-template string arrays — the TS#33304 limit, the same reason gql.tada
//! uses the call form `graphql("...")`).
//!
//! ```ts
//! // ...augments @surrealguard/client with:
//! //   "SELECT name FROM person WHERE team = $team":
//! //     { result: Array<{ name: string }>; params: { team: string } }
//! await db.query("SELECT name FROM person WHERE team = $team", { team: "red" });
//! //    ^ Promise<Array<{ name: string }>>, params required + typed from the text
//! ```

use surrealguard_workspace::analysis::ParamInference;

/// One embedded query's generated entry.
pub struct QueryEntry {
    /// The template's static parts, in order (one part, no substitutions,
    /// for a plain template).
    pub parts: Vec<String>,
    /// The inferred response kind rendered as TypeScript.
    pub result_type: String,
    /// The query's inferred parameters (named + `__hostN` substitutions).
    pub params: Vec<ParamInference>,
}

/// Renders the complete generated declaration file.
pub fn render_registry(entries: &[QueryEntry]) -> String {
    let mut rows = Vec::new();
    let mut seen = std::collections::BTreeSet::new();
    for entry in entries {
        // Call-form queries have exactly one part; template queries key
        // by their joined static parts and stay reachable for future
        // template typing.
        let key = entry.parts.join("${}");
        if !seen.insert(key.clone()) {
            continue;
        }
        rows.push(format!(
            "    {}: {{ result: {}; params: {} }};",
            ts_string(&key),
            entry.result_type,
            crate::params_type(&entry.params),
        ));
    }

    format!(
        r#"// Generated by surrealguard — do not edit.
//
// Conventions: datetime = Date, duration/uuid = string, record links =
// RecordId<"table"> (a branded string), NONE fields are optional, decimal = number.
//
// This augments the `SurqlRegistry` interface in `@surrealguard/client`, so a
// string-literal query passed to `SurrealGuardClient.query` resolves its result
// and parameter types from the entries below. Import the client's `RecordId`
// (and `GeoJSON`) types rather than redeclaring them here.

import type {{ RecordId, GeoJSON }} from "@surrealguard/client";

declare module "@surrealguard/client" {{
  interface SurqlRegistry {{
{rows}
  }}
}}

// `RecordId`/`GeoJSON` are referenced only when a query result uses them; this
// keeps the imports live regardless.
export type __SurqlGeneratedRefs = [RecordId, GeoJSON];
"#,
        rows = rows.join("\n")
    )
}

fn ts_string(text: &str) -> String {
    format!(
        "\"{}\"",
        text.replace('\\', "\\\\")
            .replace('"', "\\\"")
            .replace('\n', "\\n")
    )
}

#[cfg(test)]
mod tests {
    use super::*;
    use surrealdb_types::Kind;

    #[test]
    fn registry_renders_keys_results_subs_and_params() {
        let entries = vec![QueryEntry {
            parts: vec![
                "SELECT name FROM person WHERE age > ".into(),
                " AND team = $team".into(),
            ],
            result_type: "Array<{ name: string }>".into(),
            params: vec![
                ParamInference {
                    name: "team".into(),
                    kind: Some(Kind::String),
                    domain: None,
                    required: true,
                    spans: Vec::new(),
                },
                ParamInference {
                    name: "__host0".into(),
                    kind: Some(Kind::Int),
                    domain: None,
                    required: true,
                    spans: Vec::new(),
                },
            ],
        }];

        let rendered = render_registry(&entries);

        assert!(rendered.contains("\"SELECT name FROM person WHERE age > ${} AND team = $team\""));
        assert!(rendered.contains("result: Array<{ name: string }>;"));
        assert!(rendered.contains("params: { team: string }"));
        assert!(rendered.contains("declare module \"@surrealguard/client\""));
        assert!(rendered.contains("interface SurqlRegistry"));
        assert!(
            rendered.contains("import type { RecordId, GeoJSON } from \"@surrealguard/client\"")
        );
    }

    #[test]
    fn duplicate_query_texts_emit_one_registry_row() {
        let entry = || QueryEntry {
            parts: vec!["SELECT 1 FROM person".into()],
            result_type: "unknown".into(),
            params: Vec::new(),
        };
        let rendered = render_registry(&[entry(), entry()]);

        assert_eq!(rendered.matches("SELECT 1 FROM person").count(), 1);
    }
}
