//! The generated `.d.ts`: a literal-keyed query registry plus the `surql`
//! tag and `db.query` signatures the host code consumes.
//!
//! The typed form is the *call* form — `surql("SELECT ...")` — because
//! TypeScript infers literal types for string arguments but never for
//! tagged-template string arrays (the long-standing TS#33304 limit; the
//! same reason gql.tada uses `graphql("...")`). Tagged templates remain
//! valid input for the analyzer/LSP but type as `unknown`:
//!
//! ```ts
//! const q = surql("SELECT name FROM person WHERE team = $team");
//! //    ^ SurqlQuery<{ name: string }[], { team: string }>
//! await db.query(q, { team: "red" }); // named param: not declared in
//!                                     // TS anywhere, typed anyway
//! ```

use surrealguard_workspace::analysis::ParamInference;

/// One embedded query's generated entry.
pub struct QueryEntry {
    /// The template's static parts, in order (one part, no substitutions,
    /// for a plain template).
    pub parts: Vec<String>,
    /// The inferred response kind rendered as TypeScript.
    pub result_type: String,
    /// The query's inferred parameters (named + `__hostN` substitutions).
    pub params: Vec<ParamInference>,
}

/// Renders the complete generated declaration file.
pub fn render_registry(entries: &[QueryEntry]) -> String {
    let mut rows = Vec::new();
    let mut seen = std::collections::BTreeSet::new();
    for entry in entries {
        // Call-form queries have exactly one part; template queries key
        // by their joined static parts and stay reachable for future
        // template typing.
        let key = entry.parts.join("${}");
        if !seen.insert(key.clone()) {
            continue;
        }
        rows.push(format!(
            "  {}: {{\n    result: {};\n    subs: {};\n    params: {};\n  }};",
            ts_string(&key),
            entry.result_type,
            crate::subs_tuple(&entry.params),
            crate::params_type(&entry.params),
        ));
    }

    format!(
        r#"// Generated by surrealguard — do not edit.
//
// Conventions: datetime = Date, duration/uuid = string, record links =
// RecordId<"table"> (a branded string), NONE fields are optional,
// decimal = number.

declare type RecordId<T extends string = string> = string & {{ __table?: T }};
declare type GeoJSON = {{ type: string; coordinates: unknown }};

/** Every analyzed query, keyed by its template's static parts joined by "${{}}". */
interface SurqlRegistry {{
{rows}
}}

/** A typed query value: carries its result/params types to `db.query`. */
declare interface SurqlQuery<Result, Params> {{
  readonly text: string;
  readonly __result?: Result;
  readonly __params?: Params;
}}

/** The typed form: a string-literal query resolves through the registry.
 * (TypeScript cannot infer literal types from tagged templates, so the
 * template form below types as `unknown` — the analyzer still checks
 * both.) */
declare function surql<Q extends string>(
  query: Q
): Q extends keyof SurqlRegistry
  ? SurqlQuery<SurqlRegistry[Q]["result"], SurqlRegistry[Q]["params"]>
  : SurqlQuery<unknown, Record<string, unknown>>;
declare function surql(
  strings: TemplateStringsArray,
  ...subs: unknown[]
): SurqlQuery<unknown, Record<string, unknown>>;

/** Named-parameter query execution: the params object is required
 * exactly when the query reads parameters, and its shape is inferred
 * from the query text — nothing is declared at the call site. */
declare interface SurqlClient {{
  query<Result, Params extends Record<string, never>>(
    query: SurqlQuery<Result, Params>
  ): Promise<Result>;
  query<Result, Params>(
    query: SurqlQuery<Result, Params>,
    params: Params
  ): Promise<Result>;
}}
"#,
        rows = rows.join("\n")
    )
}

fn ts_string(text: &str) -> String {
    format!(
        "\"{}\"",
        text.replace('\\', "\\\\")
            .replace('"', "\\\"")
            .replace('\n', "\\n")
    )
}

#[cfg(test)]
mod tests {
    use super::*;
    use surrealdb_types::Kind;

    #[test]
    fn registry_renders_keys_results_subs_and_params() {
        let entries = vec![QueryEntry {
            parts: vec![
                "SELECT name FROM person WHERE age > ".into(),
                " AND team = $team".into(),
            ],
            result_type: "Array<{ name: string }>".into(),
            params: vec![
                ParamInference {
                    name: "team".into(),
                    kind: Some(Kind::String),
                    domain: None,
                    required: true,
                    spans: Vec::new(),
                },
                ParamInference {
                    name: "__host0".into(),
                    kind: Some(Kind::Int),
                    domain: None,
                    required: true,
                    spans: Vec::new(),
                },
            ],
        }];

        let rendered = render_registry(&entries);

        assert!(rendered.contains("\"SELECT name FROM person WHERE age > ${} AND team = $team\""));
        assert!(rendered.contains("result: Array<{ name: string }>;"));
        assert!(rendered.contains("subs: [number];"));
        assert!(rendered.contains("params: { team: string };"));
        assert!(rendered.contains("declare function surql"));
        assert!(rendered.contains("interface SurqlClient"));
    }

    #[test]
    fn duplicate_query_texts_emit_one_registry_row() {
        let entry = || QueryEntry {
            parts: vec!["SELECT 1 FROM person".into()],
            result_type: "unknown".into(),
            params: Vec::new(),
        };
        let rendered = render_registry(&[entry(), entry()]);

        assert_eq!(rendered.matches("SELECT 1 FROM person").count(), 1);
    }
}
