[package]
name = "surrealguard-cli"
version.workspace = true
edition.workspace = true

[dependencies]
#surrealguard-core = { path = "../core" }
surrealdb.workspace = true
surrealguard-macros = { path = "../macros" }
