//! Auto-generate TypeScript types from workspace schema.
//!
//! On save, regenerates a `.ts` file with interfaces for all tables
//! and typed functions for all query files. The output path is
//! `<workspace_root>/surrealguard.d.ts` by default.

use std::fmt::Write;
use std::path::PathBuf;

use surrealguard_analyzer::context::{Context, SchemaMode, TableKind};
use surrealguard_analyzer::types::{display_kind, Kind, Literal};

use crate::workspace::Workspace;

/// Generate TypeScript declarations from the workspace state.
pub fn generate_from_workspace(workspace: &Workspace) -> Option<(PathBuf, String)> {
    let root = workspace.roots.first()?;
    let output_path = root.join("surrealguard.d.ts");

    // Build context from all documents
    let mut ctx = Context::new();
    for doc in workspace.documents() {
        if doc.text.trim().is_empty() {
            continue;
        }
        let _ = surrealguard_analyzer::analyze_with_context(&doc.text, &mut ctx);
        ctx.take_diagnostics();
    }

    let mut out = String::new();
    writeln!(out, "// Auto-generated by surrealguard — do not edit").ok();
    writeln!(out, "// Regenerated on save by surrealguard-lsp\n").ok();

    // Generate interfaces for each table
    let mut tables: Vec<&str> = ctx.table_names().collect();
    tables.sort();

    for table_name in &tables {
        let table = match ctx.get_table(table_name) {
            Some(t) => t,
            None => continue,
        };

        let ts_name = pascal_case(table_name);

        // Skip relation tables as standalone interfaces (they're edge tables)
        let is_relation = matches!(table.kind, TableKind::Relation { .. });

        writeln!(out, "export interface {} {{", ts_name).ok();
        writeln!(out, "  id: string;").ok();

        if is_relation {
            if let TableKind::Relation { from, to } = &table.kind {
                if let Some(from_tables) = from {
                    let from_type = from_tables.iter()
                        .map(|t| pascal_case(t))
                        .collect::<Vec<_>>()
                        .join(" | ");
                    writeln!(out, "  in: {};", from_type).ok();
                }
                if let Some(to_tables) = to {
                    let to_type = to_tables.iter()
                        .map(|t| pascal_case(t))
                        .collect::<Vec<_>>()
                        .join(" | ");
                    writeln!(out, "  out: {};", to_type).ok();
                }
            }
        }

        for field in ctx.get_fields(table_name) {
            let ts_type = kind_to_ts(field.typ.as_ref().unwrap_or(&Kind::Any));
            let optional = matches!(field.typ, Some(Kind::Option(_)));
            if optional {
                writeln!(out, "  {}?: {};", field.name, ts_type).ok();
            } else {
                writeln!(out, "  {}: {};", field.name, ts_type).ok();
            }
        }

        writeln!(out, "}}\n").ok();
    }

    Some((output_path, out))
}

fn kind_to_ts(kind: &Kind) -> String {
    match kind {
        Kind::String => "string".into(),
        Kind::Int | Kind::Float | Kind::Decimal | Kind::Number => "number".into(),
        Kind::Bool => "boolean".into(),
        Kind::Datetime => "string".into(),
        Kind::Uuid => "string".into(),
        Kind::Duration => "string".into(),
        Kind::Bytes => "Uint8Array".into(),
        Kind::Null => "null".into(),
        Kind::Any => "unknown".into(),
        Kind::Object => "Record<string, unknown>".into(),
        Kind::Array(inner, _) => format!("{}[]", kind_to_ts(inner)),
        Kind::Set(inner, _) => format!("{}[]", kind_to_ts(inner)),
        Kind::Option(inner) => format!("{} | null", kind_to_ts(inner)),
        Kind::Record(tables) => {
            if tables.is_empty() {
                "{ id: string }".into()
            } else {
                tables.iter()
                    .map(|t| pascal_case(&t.to_string()))
                    .collect::<Vec<_>>()
                    .join(" | ")
            }
        }
        Kind::Either(variants) => {
            variants.iter()
                .map(|v| kind_to_ts(v))
                .collect::<Vec<_>>()
                .join(" | ")
        }
        Kind::Literal(Literal::Object(fields)) => {
            let entries: Vec<String> = fields.iter()
                .map(|(k, v)| format!("{}: {}", k, kind_to_ts(v)))
                .collect();
            format!("{{ {} }}", entries.join("; "))
        }
        Kind::Geometry(_) => "GeoJSON".into(),
        Kind::Range => "{ begin: unknown; end: unknown }".into(),
        _ => "unknown".into(),
    }
}

fn pascal_case(s: &str) -> String {
    s.split('_')
        .map(|word| {
            let mut chars = word.chars();
            match chars.next() {
                Some(c) => c.to_uppercase().to_string() + &chars.as_str().to_lowercase(),
                None => String::new(),
            }
        })
        .collect()
}
