[package]
name = "surrealguard-macros"
version.workspace = true
edition.workspace = true

[lib]
proc-macro = true

[dependencies]
surrealdb.workspace = true

# Macro specific dependencies
syn = { version = "2.0", features = [] }
quote = "1.0"
proc-macro2 = "1.0"
