[package]
name = "surrealguard-codegen"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
readme = "README.md"
keywords.workspace = true
categories.workspace = true
description = "TypeScript type generation from SurrealGuard analysis results"

[dependencies]
surrealdb-types.workspace = true
surrealguard-workspace = { path = "../workspace", version = "0.4.0" }

[lints]
workspace = true
