[package]
name = "surrealguard-codegen"
version.workspace = true
edition.workspace = true

[dependencies]
surrealguard-core = { path = "../core" }

# Codegen specific dependencies
convert_case = "0.6"
handlebars = "4.3"   # For template-based code generation
prettyplease = "0.2" # For Rust code formatting
