//! The built-in SurrealQL function catalog, for completion.
//!
//! Every entry is derived mechanically from the analyzer's own dispatch
//! tables (`analyzer::function::<family>::mod.rs`, the `match path` arms —
//! the authoritative set of names the engine resolves) and from each
//! function analyzer's module doc comment, which states the documented
//! signature. Completion therefore never offers a name the analyzer would
//! reject as unknown (5001).
//!
//! `builtins_cover_every_dispatch_arm` in `super` re-derives the arm set from
//! those sources at test time, so a builtin added to the analyzer without
//! being added here fails the suite.

/// One built-in function: the name as written in SurrealQL, its documented
/// parameter list, and its documented return type. `params`/`returns` are
/// empty for the handful of API-middleware entries whose signature the
/// analyzer records as unverified.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub(crate) struct Builtin {
    /// The call path as written (`string::len`, `type::is::record`).
    pub name: &'static str,
    /// The documented parameter list, without the surrounding parentheses.
    pub params: &'static str,
    /// The documented return type, as written in the docs.
    pub returns: &'static str,
}

impl Builtin {
    /// `string::len(string) -> int`, the one-line signature shown as a
    /// completion item's detail.
    pub fn signature(&self) -> String {
        if self.returns.is_empty() {
            format!("{}({})", self.name, self.params)
        } else {
            format!("{}({}) -> {}", self.name, self.params, self.returns)
        }
    }

    /// The leading namespace (`string`, `math`, `fn`), which is the family a
    /// method call on a typed receiver dispatches to.
    pub fn family(&self) -> &'static str {
        match self.name.split_once("::") {
            Some((head, _)) => head,
            None => self.name,
        }
    }
}

/// Every built-in the analyzer resolves, sorted by name.
pub(crate) static BUILTINS: &[Builtin] = &[
    Builtin { name: "api::invoke", params: "path: string[, options]", returns: "any" },
    Builtin { name: "api::req::body", params: "", returns: "" },
    Builtin { name: "api::res::body", params: "", returns: "" },
    Builtin { name: "api::res::header", params: "", returns: "" },
    Builtin { name: "api::res::headers", params: "", returns: "" },
    Builtin { name: "api::res::status", params: "", returns: "" },
    Builtin { name: "api::timeout", params: "", returns: "" },
    Builtin { name: "array::add", params: "array, value", returns: "array" },
    Builtin { name: "array::all", params: "array", returns: "bool" },
    Builtin { name: "array::any", params: "array", returns: "bool" },
    Builtin { name: "array::append", params: "array, value", returns: "array" },
    Builtin { name: "array::at", params: "array, index", returns: "element" },
    Builtin { name: "array::boolean_and", params: "array, array", returns: "array<bool>" },
    Builtin { name: "array::boolean_not", params: "array", returns: "array<bool>" },
    Builtin { name: "array::boolean_or", params: "array, array", returns: "array<bool>" },
    Builtin { name: "array::boolean_xor", params: "array, array", returns: "array<bool>" },
    Builtin { name: "array::clump", params: "array, size", returns: "array<array>" },
    Builtin { name: "array::combine", params: "array, array", returns: "array" },
    Builtin { name: "array::complement", params: "array, array", returns: "array" },
    Builtin { name: "array::concat", params: "array, array, ...", returns: "array" },
    Builtin { name: "array::difference", params: "array, array", returns: "array" },
    Builtin { name: "array::distinct", params: "array", returns: "array" },
    Builtin { name: "array::every", params: "", returns: "" },
    Builtin { name: "array::fill", params: "array, value, [start], [end]", returns: "array" },
    Builtin { name: "array::filter", params: "array, closure", returns: "array" },
    Builtin { name: "array::filter_index", params: "array, value", returns: "array<int>" },
    Builtin { name: "array::find", params: "array, value", returns: "element" },
    Builtin { name: "array::find_index", params: "array, value", returns: "int" },
    Builtin { name: "array::first", params: "array", returns: "element" },
    Builtin { name: "array::flatten", params: "array", returns: "array" },
    Builtin { name: "array::fold", params: "set, init, closure", returns: "accumulated" },
    Builtin { name: "array::group", params: "array", returns: "array" },
    Builtin { name: "array::includes", params: "", returns: "" },
    Builtin { name: "array::index_of", params: "", returns: "" },
    Builtin { name: "array::insert", params: "array, value, [index]", returns: "array" },
    Builtin { name: "array::intersect", params: "array, array", returns: "array" },
    Builtin { name: "array::is_empty", params: "array", returns: "bool" },
    Builtin { name: "array::join", params: "array, separator", returns: "string" },
    Builtin { name: "array::last", params: "array", returns: "element" },
    Builtin { name: "array::len", params: "array", returns: "int" },
    Builtin { name: "array::logical_and", params: "array, array", returns: "array" },
    Builtin { name: "array::logical_or", params: "array, array", returns: "array" },
    Builtin { name: "array::logical_xor", params: "array, array", returns: "array" },
    Builtin { name: "array::map", params: "array, closure", returns: "array" },
    Builtin { name: "array::matches", params: "array, value", returns: "array<bool>" },
    Builtin { name: "array::max", params: "array", returns: "element" },
    Builtin { name: "array::min", params: "array", returns: "element" },
    Builtin { name: "array::pop", params: "array", returns: "element" },
    Builtin { name: "array::prepend", params: "array, value", returns: "array" },
    Builtin { name: "array::push", params: "array, value", returns: "array" },
    Builtin { name: "array::range", params: "start, count", returns: "array<int>" },
    Builtin { name: "array::reduce", params: "set, closure", returns: "accumulated" },
    Builtin { name: "array::remove", params: "array, index", returns: "array" },
    Builtin { name: "array::repeat", params: "value, count", returns: "array" },
    Builtin { name: "array::reverse", params: "array", returns: "array" },
    Builtin { name: "array::sequence", params: "offset, len?", returns: "array<int>" },
    Builtin { name: "array::shuffle", params: "array", returns: "array" },
    Builtin { name: "array::slice", params: "array, [start], [len]", returns: "array" },
    Builtin { name: "array::some", params: "", returns: "" },
    Builtin { name: "array::sort", params: "array, [direction]", returns: "array" },
    Builtin { name: "array::sort::asc", params: "array", returns: "array" },
    Builtin { name: "array::sort::desc", params: "array", returns: "array" },
    Builtin { name: "array::sort_lexical", params: "array, [direction]", returns: "array" },
    Builtin { name: "array::sort_natural", params: "array, [direction]", returns: "array" },
    Builtin { name: "array::sort_natural_lexical", params: "array, [direction]", returns: "array" },
    Builtin { name: "array::swap", params: "array, from, to", returns: "array" },
    Builtin { name: "array::transpose", params: "array", returns: "array" },
    Builtin { name: "array::union", params: "array, array, ...", returns: "array" },
    Builtin { name: "array::windows", params: "array, size", returns: "array<array>" },
    Builtin { name: "bytes::len", params: "bytes", returns: "int" },
    Builtin { name: "count", params: "value", returns: "int" },
    Builtin { name: "crypto::argon2::compare", params: "string, string", returns: "bool" },
    Builtin { name: "crypto::argon2::generate", params: "string", returns: "string" },
    Builtin { name: "crypto::bcrypt::compare", params: "string, string", returns: "bool" },
    Builtin { name: "crypto::bcrypt::generate", params: "string", returns: "string" },
    Builtin { name: "crypto::blake3", params: "string", returns: "string" },
    Builtin { name: "crypto::joaat", params: "string", returns: "string" },
    Builtin { name: "crypto::md5", params: "string", returns: "string" },
    Builtin { name: "crypto::pbkdf2::compare", params: "string, string", returns: "bool" },
    Builtin { name: "crypto::pbkdf2::generate", params: "string", returns: "string" },
    Builtin { name: "crypto::scrypt::compare", params: "string, string", returns: "bool" },
    Builtin { name: "crypto::scrypt::generate", params: "string", returns: "string" },
    Builtin { name: "crypto::sha1", params: "string", returns: "string" },
    Builtin { name: "crypto::sha256", params: "string", returns: "string" },
    Builtin { name: "crypto::sha512", params: "string", returns: "string" },
    Builtin { name: "duration::days", params: "duration", returns: "int" },
    Builtin { name: "duration::from::days", params: "number", returns: "duration" },
    Builtin { name: "duration::from::hours", params: "number", returns: "duration" },
    Builtin { name: "duration::from::micros", params: "number", returns: "duration" },
    Builtin { name: "duration::from::millis", params: "number", returns: "duration" },
    Builtin { name: "duration::from::mins", params: "number", returns: "duration" },
    Builtin { name: "duration::from::nanos", params: "number", returns: "duration" },
    Builtin { name: "duration::from::secs", params: "number", returns: "duration" },
    Builtin { name: "duration::from::weeks", params: "number", returns: "duration" },
    Builtin { name: "duration::hours", params: "duration", returns: "int" },
    Builtin { name: "duration::micros", params: "duration", returns: "int" },
    Builtin { name: "duration::millis", params: "duration", returns: "int" },
    Builtin { name: "duration::mins", params: "duration", returns: "int" },
    Builtin { name: "duration::nanos", params: "duration", returns: "int" },
    Builtin { name: "duration::secs", params: "duration", returns: "int" },
    Builtin { name: "duration::weeks", params: "duration", returns: "int" },
    Builtin { name: "duration::years", params: "duration", returns: "int" },
    Builtin { name: "encoding::base64::decode", params: "string", returns: "bytes" },
    Builtin { name: "encoding::base64::encode", params: "bytes", returns: "string" },
    Builtin { name: "encoding::cbor::decode", params: "bytes", returns: "any" },
    Builtin { name: "encoding::cbor::encode", params: "any", returns: "bytes" },
    Builtin { name: "encoding::json::decode", params: "string", returns: "object | array | string | number | bool | null" },
    Builtin { name: "encoding::json::encode", params: "any", returns: "string" },
    Builtin { name: "eval::gql", params: "query: string, bindings?: object", returns: "any" },
    Builtin { name: "eval::surql", params: "query: string, bindings?: object", returns: "any" },
    Builtin { name: "file::bucket", params: "file", returns: "string" },
    Builtin { name: "file::copy", params: "file, target", returns: "any" },
    Builtin { name: "file::copy_if_not_exists", params: "file, target", returns: "any" },
    Builtin { name: "file::delete", params: "file", returns: "any" },
    Builtin { name: "file::exists", params: "file", returns: "bool" },
    Builtin { name: "file::get", params: "file", returns: "bytes" },
    Builtin { name: "file::head", params: "file", returns: "object" },
    Builtin { name: "file::key", params: "file", returns: "string" },
    Builtin { name: "file::list", params: "bucket: string, opts: option<object>", returns: "array<object>" },
    Builtin { name: "file::put", params: "file, value: any", returns: "any" },
    Builtin { name: "file::put_if_not_exists", params: "file, value: any", returns: "any" },
    Builtin { name: "file::rename", params: "file, target", returns: "any" },
    Builtin { name: "file::rename_if_not_exists", params: "file, target", returns: "any" },
    Builtin { name: "geo::area", params: "geometry", returns: "number" },
    Builtin { name: "geo::bearing", params: "geometry, geometry", returns: "number" },
    Builtin { name: "geo::centroid", params: "geometry", returns: "geometry<point>" },
    Builtin { name: "geo::distance", params: "geometry, geometry", returns: "number" },
    Builtin { name: "geo::hash::decode", params: "string", returns: "geometry<point>" },
    Builtin { name: "geo::hash::encode", params: "geometry, int?", returns: "string" },
    Builtin { name: "geo::is_valid", params: "geometry", returns: "bool" },
    Builtin { name: "http::delete", params: "url, ...", returns: "body" },
    Builtin { name: "http::get", params: "url, ...", returns: "body" },
    Builtin { name: "http::head", params: "url: string, headers: option<object>", returns: "any" },
    Builtin { name: "http::patch", params: "url, ...", returns: "body" },
    Builtin { name: "http::post", params: "url, ...", returns: "body" },
    Builtin { name: "http::put", params: "url, ...", returns: "body" },
    Builtin { name: "math::abs", params: "number", returns: "number" },
    Builtin { name: "math::acos", params: "number", returns: "number" },
    Builtin { name: "math::acot", params: "number", returns: "number" },
    Builtin { name: "math::asin", params: "number", returns: "number" },
    Builtin { name: "math::atan", params: "number", returns: "number" },
    Builtin { name: "math::bottom", params: "array<number>, count", returns: "array<number>" },
    Builtin { name: "math::ceil", params: "number", returns: "number" },
    Builtin { name: "math::clamp", params: "number, min, max", returns: "number" },
    Builtin { name: "math::cos", params: "number", returns: "number" },
    Builtin { name: "math::cot", params: "number", returns: "number" },
    Builtin { name: "math::deg2rad", params: "number", returns: "number" },
    Builtin { name: "math::fixed", params: "number, places", returns: "number" },
    Builtin { name: "math::floor", params: "number", returns: "number" },
    Builtin { name: "math::interquartile", params: "array<number>", returns: "number" },
    Builtin { name: "math::lerp", params: "number, number, fraction", returns: "number" },
    Builtin { name: "math::lerpangle", params: "number, number, fraction", returns: "number" },
    Builtin { name: "math::ln", params: "number", returns: "number" },
    Builtin { name: "math::log", params: "number, base", returns: "number" },
    Builtin { name: "math::log10", params: "number", returns: "number" },
    Builtin { name: "math::log2", params: "number", returns: "number" },
    Builtin { name: "math::max", params: "array<number>", returns: "number" },
    Builtin { name: "math::mean", params: "array<number>", returns: "number" },
    Builtin { name: "math::median", params: "array<number>", returns: "number" },
    Builtin { name: "math::midhinge", params: "array<number>", returns: "number" },
    Builtin { name: "math::min", params: "array<number>", returns: "number" },
    Builtin { name: "math::mode", params: "array<number>", returns: "number" },
    Builtin { name: "math::nearestrank", params: "array<number>, percentile", returns: "number" },
    Builtin { name: "math::percentile", params: "array<number>, percentile", returns: "number" },
    Builtin { name: "math::pow", params: "number, exponent", returns: "number" },
    Builtin { name: "math::product", params: "array<number>", returns: "number" },
    Builtin { name: "math::rad2deg", params: "number", returns: "number" },
    Builtin { name: "math::round", params: "number", returns: "number" },
    Builtin { name: "math::sign", params: "number", returns: "number" },
    Builtin { name: "math::sin", params: "number", returns: "number" },
    Builtin { name: "math::spread", params: "array<number>", returns: "number" },
    Builtin { name: "math::sqrt", params: "number", returns: "number" },
    Builtin { name: "math::stddev", params: "array<number>", returns: "number" },
    Builtin { name: "math::sum", params: "array<number>", returns: "number" },
    Builtin { name: "math::tan", params: "number", returns: "number" },
    Builtin { name: "math::top", params: "array<number>, count", returns: "array<number>" },
    Builtin { name: "math::trimean", params: "array<number>", returns: "number" },
    Builtin { name: "math::variance", params: "array<number>", returns: "number" },
    Builtin { name: "meta::id", params: "record", returns: "any" },
    Builtin { name: "meta::table", params: "record", returns: "table" },
    Builtin { name: "meta::tb", params: "record", returns: "string" },
    Builtin { name: "not::not", params: "", returns: "" },
    Builtin { name: "object::entries", params: "object", returns: "array<array<any>>" },
    Builtin { name: "object::extend", params: "object, object", returns: "object" },
    Builtin { name: "object::from_entries", params: "array", returns: "object" },
    Builtin { name: "object::is_empty", params: "object", returns: "bool" },
    Builtin { name: "object::keys", params: "object", returns: "array<string>" },
    Builtin { name: "object::len", params: "object", returns: "int" },
    Builtin { name: "object::remove", params: "object, string", returns: "object" },
    Builtin { name: "object::values", params: "object", returns: "array" },
    Builtin { name: "parse::email::host", params: "string", returns: "string" },
    Builtin { name: "parse::email::user", params: "string", returns: "string" },
    Builtin { name: "parse::url::domain", params: "string", returns: "string" },
    Builtin { name: "parse::url::fragment", params: "string", returns: "string" },
    Builtin { name: "parse::url::host", params: "string", returns: "string" },
    Builtin { name: "parse::url::path", params: "string", returns: "string" },
    Builtin { name: "parse::url::port", params: "string", returns: "int" },
    Builtin { name: "parse::url::query", params: "string", returns: "string" },
    Builtin { name: "parse::url::scheme", params: "string", returns: "string" },
    Builtin { name: "rand", params: "", returns: "float" },
    Builtin { name: "rand::bool", params: "", returns: "bool" },
    Builtin { name: "rand::duration", params: "min?, max?", returns: "duration" },
    Builtin { name: "rand::enum", params: "a, b, ...", returns: "a | b | ..." },
    Builtin { name: "rand::float", params: "min?, max?", returns: "float" },
    Builtin { name: "rand::guid", params: "length?, max?", returns: "string" },
    Builtin { name: "rand::id", params: "(Optional<int>, Optional<int>)", returns: "string" },
    Builtin { name: "rand::int", params: "min?, max?", returns: "int" },
    Builtin { name: "rand::string", params: "length?, max?", returns: "string" },
    Builtin { name: "rand::time", params: "min?, max?", returns: "datetime" },
    Builtin { name: "rand::ulid", params: "datetime?", returns: "string" },
    Builtin { name: "rand::uuid", params: "", returns: "uuid" },
    Builtin { name: "rand::uuid::v4", params: "", returns: "uuid" },
    Builtin { name: "rand::uuid::v7", params: "datetime?", returns: "uuid" },
    Builtin { name: "record::exists", params: "record", returns: "bool" },
    Builtin { name: "record::id", params: "record", returns: "any" },
    Builtin { name: "record::is_edge", params: "record", returns: "bool" },
    Builtin { name: "record::refs", params: "record, ...", returns: "array<any>" },
    Builtin { name: "record::table", params: "record", returns: "table" },
    Builtin { name: "record::tb", params: "record", returns: "string" },
    Builtin { name: "schema::table::exists", params: "string", returns: "bool" },
    Builtin { name: "search::analyze", params: "string, string", returns: "array<string>" },
    Builtin { name: "search::highlight", params: "string, string, number [, bool]", returns: "string" },
    Builtin { name: "search::linear", params: "array, ...", returns: "float" },
    Builtin { name: "search::offsets", params: "number [, bool]", returns: "object" },
    Builtin { name: "search::rrf", params: "array, ...", returns: "float" },
    Builtin { name: "search::score", params: "number", returns: "float" },
    Builtin { name: "sequence::next", params: "string", returns: "int" },
    Builtin { name: "sequence::nextval", params: "string", returns: "int" },
    Builtin { name: "session::ac", params: "", returns: "option<string>" },
    Builtin { name: "session::db", params: "", returns: "option<string>" },
    Builtin { name: "session::id", params: "", returns: "option<string>" },
    Builtin { name: "session::ip", params: "", returns: "option<string>" },
    Builtin { name: "session::ns", params: "", returns: "option<string>" },
    Builtin { name: "session::origin", params: "", returns: "option<string>" },
    Builtin { name: "session::rd", params: "", returns: "option<record>" },
    Builtin { name: "session::sc", params: "", returns: "option<string>" },
    Builtin { name: "session::sd", params: "", returns: "option<record>" },
    Builtin { name: "session::token", params: "", returns: "option<string>" },
    Builtin { name: "set::add", params: "set, value", returns: "set" },
    Builtin { name: "set::all", params: "set", returns: "bool" },
    Builtin { name: "set::any", params: "set", returns: "bool" },
    Builtin { name: "set::at", params: "set, int", returns: "element" },
    Builtin { name: "set::complement", params: "set, set", returns: "set" },
    Builtin { name: "set::contains", params: "set, value", returns: "bool" },
    Builtin { name: "set::difference", params: "set, set", returns: "set" },
    Builtin { name: "set::filter", params: "set, closure", returns: "set" },
    Builtin { name: "set::find", params: "set, value", returns: "element" },
    Builtin { name: "set::first", params: "set", returns: "element" },
    Builtin { name: "set::flatten", params: "set", returns: "set" },
    Builtin { name: "set::fold", params: "", returns: "" },
    Builtin { name: "set::intersect", params: "set, set", returns: "set" },
    Builtin { name: "set::is_empty", params: "set", returns: "bool" },
    Builtin { name: "set::join", params: "set, separator", returns: "string" },
    Builtin { name: "set::last", params: "set", returns: "element" },
    Builtin { name: "set::len", params: "set", returns: "int" },
    Builtin { name: "set::map", params: "set, closure", returns: "set" },
    Builtin { name: "set::max", params: "set", returns: "element" },
    Builtin { name: "set::min", params: "set", returns: "element" },
    Builtin { name: "set::reduce", params: "", returns: "" },
    Builtin { name: "set::remove", params: "set, int", returns: "set" },
    Builtin { name: "set::slice", params: "set, start, len", returns: "set" },
    Builtin { name: "set::union", params: "set, set", returns: "set" },
    Builtin { name: "sleep::sleep", params: "", returns: "" },
    Builtin { name: "string::capitalize", params: "string", returns: "string" },
    Builtin { name: "string::concat", params: "...any", returns: "string" },
    Builtin { name: "string::contains", params: "string, string", returns: "bool" },
    Builtin { name: "string::distance::damerau_levenshtein", params: "string, string", returns: "int" },
    Builtin { name: "string::distance::hamming", params: "string, string", returns: "int" },
    Builtin { name: "string::distance::levenshtein", params: "string, string", returns: "int" },
    Builtin { name: "string::distance::normalized_damerau_levenshtein", params: "string, string", returns: "float" },
    Builtin { name: "string::distance::normalized_levenshtein", params: "string, string", returns: "float" },
    Builtin { name: "string::distance::osa", params: "string, string", returns: "int" },
    Builtin { name: "string::ends_with", params: "string, string", returns: "bool" },
    Builtin { name: "string::html::encode", params: "string", returns: "string" },
    Builtin { name: "string::html::sanitize", params: "string", returns: "string" },
    Builtin { name: "string::is_alpha", params: "string", returns: "bool" },
    Builtin { name: "string::is_alphanum", params: "string", returns: "bool" },
    Builtin { name: "string::is_ascii", params: "string", returns: "bool" },
    Builtin { name: "string::is_datetime", params: "string, string", returns: "bool" },
    Builtin { name: "string::is_domain", params: "string", returns: "bool" },
    Builtin { name: "string::is_email", params: "string", returns: "bool" },
    Builtin { name: "string::is_hexadecimal", params: "string", returns: "bool" },
    Builtin { name: "string::is_ip", params: "string", returns: "bool" },
    Builtin { name: "string::is_ipv4", params: "string", returns: "bool" },
    Builtin { name: "string::is_ipv6", params: "string", returns: "bool" },
    Builtin { name: "string::is_latitude", params: "string", returns: "bool" },
    Builtin { name: "string::is_longitude", params: "string", returns: "bool" },
    Builtin { name: "string::is_numeric", params: "string", returns: "bool" },
    Builtin { name: "string::is_record", params: "string, string", returns: "bool" },
    Builtin { name: "string::is_semver", params: "string", returns: "bool" },
    Builtin { name: "string::is_ulid", params: "string", returns: "bool" },
    Builtin { name: "string::is_url", params: "string", returns: "bool" },
    Builtin { name: "string::is_uuid", params: "string", returns: "bool" },
    Builtin { name: "string::join", params: "separator, ...string", returns: "string" },
    Builtin { name: "string::len", params: "string", returns: "int" },
    Builtin { name: "string::lowercase", params: "string", returns: "string" },
    Builtin { name: "string::matches", params: "string, string", returns: "bool" },
    Builtin { name: "string::repeat", params: "string, int", returns: "string" },
    Builtin { name: "string::replace", params: "string, string, string", returns: "string" },
    Builtin { name: "string::reverse", params: "string", returns: "string" },
    Builtin { name: "string::semver::compare", params: "string, string", returns: "int" },
    Builtin { name: "string::semver::inc::major", params: "string", returns: "string" },
    Builtin { name: "string::semver::inc::minor", params: "string", returns: "string" },
    Builtin { name: "string::semver::inc::patch", params: "string", returns: "string" },
    Builtin { name: "string::semver::major", params: "string", returns: "int" },
    Builtin { name: "string::semver::minor", params: "string", returns: "int" },
    Builtin { name: "string::semver::patch", params: "string", returns: "int" },
    Builtin { name: "string::semver::set::major", params: "string, int", returns: "string" },
    Builtin { name: "string::semver::set::minor", params: "string, int", returns: "string" },
    Builtin { name: "string::semver::set::patch", params: "string, int", returns: "string" },
    Builtin { name: "string::similarity::fuzzy", params: "string, string", returns: "int" },
    Builtin { name: "string::similarity::jaro", params: "string, string", returns: "float" },
    Builtin { name: "string::similarity::jaro_winkler", params: "string, string", returns: "float" },
    Builtin { name: "string::similarity::smithwaterman", params: "string, string", returns: "int" },
    Builtin { name: "string::similarity::sorensen_dice", params: "string, string", returns: "float" },
    Builtin { name: "string::slice", params: "string, int, int", returns: "string" },
    Builtin { name: "string::slug", params: "string", returns: "string" },
    Builtin { name: "string::split", params: "string, string", returns: "array<string>" },
    Builtin { name: "string::starts_with", params: "string, string", returns: "bool" },
    Builtin { name: "string::trim", params: "string", returns: "string" },
    Builtin { name: "string::uppercase", params: "string", returns: "string" },
    Builtin { name: "string::words", params: "string", returns: "array<string>" },
    Builtin { name: "time::ceil", params: "datetime, duration", returns: "datetime" },
    Builtin { name: "time::day", params: "datetime", returns: "int" },
    Builtin { name: "time::floor", params: "datetime, duration", returns: "datetime" },
    Builtin { name: "time::format", params: "datetime, string", returns: "string" },
    Builtin { name: "time::from::micros", params: "number", returns: "datetime" },
    Builtin { name: "time::from::millis", params: "number", returns: "datetime" },
    Builtin { name: "time::from::nanos", params: "number", returns: "datetime" },
    Builtin { name: "time::from::secs", params: "number", returns: "datetime" },
    Builtin { name: "time::from::unix", params: "number", returns: "datetime" },
    Builtin { name: "time::from_ulid", params: "string", returns: "datetime" },
    Builtin { name: "time::from_uuid", params: "uuid", returns: "datetime" },
    Builtin { name: "time::group", params: "datetime, string", returns: "datetime" },
    Builtin { name: "time::hour", params: "datetime", returns: "int" },
    Builtin { name: "time::is_leap_year", params: "datetime", returns: "bool" },
    Builtin { name: "time::max", params: "array<datetime>", returns: "datetime" },
    Builtin { name: "time::micros", params: "datetime", returns: "int" },
    Builtin { name: "time::millis", params: "datetime", returns: "int" },
    Builtin { name: "time::min", params: "array<datetime>", returns: "datetime" },
    Builtin { name: "time::minute", params: "datetime", returns: "int" },
    Builtin { name: "time::month", params: "datetime", returns: "int" },
    Builtin { name: "time::nano", params: "datetime", returns: "int" },
    Builtin { name: "time::now", params: "", returns: "datetime" },
    Builtin { name: "time::round", params: "datetime, duration", returns: "datetime" },
    Builtin { name: "time::second", params: "datetime", returns: "int" },
    Builtin { name: "time::set_day", params: "datetime, int", returns: "datetime" },
    Builtin { name: "time::set_hour", params: "datetime, int", returns: "datetime" },
    Builtin { name: "time::set_minute", params: "datetime, int", returns: "datetime" },
    Builtin { name: "time::set_month", params: "datetime, int", returns: "datetime" },
    Builtin { name: "time::set_nanosecond", params: "datetime, int", returns: "datetime" },
    Builtin { name: "time::set_second", params: "datetime, int", returns: "datetime" },
    Builtin { name: "time::set_year", params: "datetime, int", returns: "datetime" },
    Builtin { name: "time::timezone", params: "", returns: "string" },
    Builtin { name: "time::unix", params: "datetime", returns: "int" },
    Builtin { name: "time::wday", params: "datetime", returns: "int" },
    Builtin { name: "time::week", params: "datetime", returns: "int" },
    Builtin { name: "time::yday", params: "datetime", returns: "int" },
    Builtin { name: "time::year", params: "datetime", returns: "int" },
    Builtin { name: "type::array", params: "any", returns: "array" },
    Builtin { name: "type::bool", params: "any", returns: "bool" },
    Builtin { name: "type::bytes", params: "any", returns: "bytes" },
    Builtin { name: "type::datetime", params: "any", returns: "datetime" },
    Builtin { name: "type::decimal", params: "any", returns: "decimal" },
    Builtin { name: "type::duration", params: "any", returns: "duration" },
    Builtin { name: "type::field", params: "path", returns: "field value" },
    Builtin { name: "type::fields", params: "paths", returns: "field values" },
    Builtin { name: "type::file", params: "bucket, key", returns: "file" },
    Builtin { name: "type::float", params: "any", returns: "float" },
    Builtin { name: "type::geometry", params: "any", returns: "geometry" },
    Builtin { name: "type::int", params: "any", returns: "int" },
    Builtin { name: "type::is::array", params: "any", returns: "bool" },
    Builtin { name: "type::is::bool", params: "any", returns: "bool" },
    Builtin { name: "type::is::bytes", params: "any", returns: "bool" },
    Builtin { name: "type::is::collection", params: "any", returns: "bool" },
    Builtin { name: "type::is::datetime", params: "any", returns: "bool" },
    Builtin { name: "type::is::decimal", params: "any", returns: "bool" },
    Builtin { name: "type::is::duration", params: "any", returns: "bool" },
    Builtin { name: "type::is::float", params: "any", returns: "bool" },
    Builtin { name: "type::is::geometry", params: "any", returns: "bool" },
    Builtin { name: "type::is::int", params: "any", returns: "bool" },
    Builtin { name: "type::is::line", params: "any", returns: "bool" },
    Builtin { name: "type::is::multiline", params: "any", returns: "bool" },
    Builtin { name: "type::is::multipoint", params: "any", returns: "bool" },
    Builtin { name: "type::is::multipolygon", params: "any", returns: "bool" },
    Builtin { name: "type::is::none", params: "any", returns: "bool" },
    Builtin { name: "type::is::null", params: "any", returns: "bool" },
    Builtin { name: "type::is::number", params: "any", returns: "bool" },
    Builtin { name: "type::is::object", params: "any", returns: "bool" },
    Builtin { name: "type::is::point", params: "any", returns: "bool" },
    Builtin { name: "type::is::polygon", params: "any", returns: "bool" },
    Builtin { name: "type::is::range", params: "any", returns: "bool" },
    Builtin { name: "type::is::record", params: "any, option<string>", returns: "bool" },
    Builtin { name: "type::is::set", params: "any", returns: "bool" },
    Builtin { name: "type::is::string", params: "any", returns: "bool" },
    Builtin { name: "type::is::uuid", params: "any", returns: "bool" },
    Builtin { name: "type::number", params: "any", returns: "number" },
    Builtin { name: "type::of", params: "value", returns: "string" },
    Builtin { name: "type::point", params: "number, number", returns: "geometry<point>" },
    Builtin { name: "type::range", params: "..", returns: "range" },
    Builtin { name: "type::record", params: "any", returns: "record" },
    Builtin { name: "type::set", params: "any", returns: "set" },
    Builtin { name: "type::string", params: "any", returns: "string" },
    Builtin { name: "type::string_lossy", params: "any", returns: "string" },
    Builtin { name: "type::table", params: "any", returns: "table" },
    Builtin { name: "type::thing", params: "table, id", returns: "record" },
    Builtin { name: "type::uuid", params: "any", returns: "uuid" },
    Builtin { name: "value::diff", params: "any, any", returns: "array<object>" },
    Builtin { name: "value::expect", params: "any, string", returns: "any" },
    Builtin { name: "value::patch", params: "any, array", returns: "any" },
    Builtin { name: "vector::add", params: "array, array", returns: "array" },
    Builtin { name: "vector::angle", params: "array, array", returns: "float" },
    Builtin { name: "vector::cross", params: "array, array", returns: "array" },
    Builtin { name: "vector::distance::chebyshev", params: "array, array", returns: "number" },
    Builtin { name: "vector::distance::euclidean", params: "array, array", returns: "number" },
    Builtin { name: "vector::distance::hamming", params: "array, array", returns: "number" },
    Builtin { name: "vector::distance::knn", params: "int?", returns: "number" },
    Builtin { name: "vector::distance::mahalanobis", params: "array, array", returns: "number" },
    Builtin { name: "vector::distance::manhattan", params: "array, array", returns: "number" },
    Builtin { name: "vector::distance::minkowski", params: "array, array, number", returns: "number" },
    Builtin { name: "vector::divide", params: "array, array", returns: "array" },
    Builtin { name: "vector::dot", params: "array, array", returns: "number" },
    Builtin { name: "vector::magnitude", params: "array", returns: "number" },
    Builtin { name: "vector::multiply", params: "array, array", returns: "array" },
    Builtin { name: "vector::normalize", params: "array", returns: "array" },
    Builtin { name: "vector::project", params: "array, array", returns: "array" },
    Builtin { name: "vector::scale", params: "array, number", returns: "array" },
    Builtin { name: "vector::similarity::cosine", params: "array, array", returns: "number" },
    Builtin { name: "vector::similarity::jaccard", params: "array, array", returns: "number" },
    Builtin { name: "vector::similarity::pearson", params: "array, array", returns: "number" },
    Builtin { name: "vector::similarity::spearman", params: "array, array", returns: "number" },
    Builtin { name: "vector::subtract", params: "array, array", returns: "array" },
];

/// Whether `path` names a built-in the analyzer resolves.
///
/// This is the *existence* oracle, deliberately separate from what a call
/// evaluates to. Several built-ins return an honest `Kind::Any` — `record::id`
/// (a record id is genuinely one of many shapes), `array::at` on an
/// `array<any>` — so "the analyzer produced `any`" cannot stand in for "no such
/// function": doing that turned `$r.id()` into a false `E5001 has no method`.
///
/// Names are canonicalized by replacing `::` with `_`, which folds the two
/// spellings of the `type::is::x` family (the catalog writes `type::is::record`,
/// lowering normalizes calls to `type::is_record`) onto one key — the same
/// canonicalization `builtins_cover_every_dispatch_arm_the_analyzer_resolves`
/// uses to prove this list matches the dispatch tables exactly.
pub(crate) fn is_builtin(path: &str) -> bool {
    static NAMES: std::sync::OnceLock<std::collections::BTreeSet<String>> =
        std::sync::OnceLock::new();
    NAMES
        .get_or_init(|| {
            BUILTINS
                .iter()
                .map(|builtin| builtin.name.replace("::", "_"))
                .collect()
        })
        .contains(&path.replace("::", "_"))
}
