[package]
name = "surrealguard-core"
version.workspace = true
edition.workspace = true
publish = false

[dependencies]
surrealdb.workspace = true
thiserror.workspace = true
surrealguard-macros.path = "../macros"
