// Generated by surrealguard — do not edit.
//
// Conventions: datetime = Date, duration/uuid = string, record links =
// RecordId<"table"> (a branded string), NONE fields are optional, decimal = number.
//
// This file re-exports a ready-to-use `SurrealGuardClient` and augments its
// `SurqlRegistry` with one entry per analyzed query, keyed by the exact query
// text. Import the client from here — a string-literal query then resolves its
// result and params from the entries below, with no separate augmentation
// import. Import the client's `RecordId` (and `GeoJSON`) types rather than
// redeclaring them here.

import type { RecordId, GeoJSON } from "@surrealguard/client";

export { SurrealGuardClient } from "@surrealguard/client";
// Re-exported so a query result using them needs only this one import.
export type { RecordId, GeoJSON } from "@surrealguard/client";

declare module "@surrealguard/client" {
  interface SurqlRegistry {
    "SELECT name FROM person WHERE team = $team": { result: [Array<{ name: string }>]; params: { team: RecordId<"team"> } };
    "SELECT name, age, team FROM person": { result: [Array<{ age: number; name: string; team: RecordId<"team"> }>]; params: Record<string, never> };
    "SELECT name FROM person; SELECT age FROM person": { result: [Array<{ name: string }>, Array<{ age: number }>]; params: Record<string, never> };
  }
}

// `RecordId`/`GeoJSON` are referenced only when a query result uses them; this
// keeps the imports live regardless.
export type __SurqlGeneratedRefs = [RecordId, GeoJSON];
