// Generated by surrealguard — do not edit.
//
// Value conventions name what the SurrealDB SDK actually decodes, which is its
// own value classes: record links are `RecordId<"table">`, uuids are `Uuid`,
// durations are `Duration`, decimals are `Decimal`. Datetimes are a native
// `Date` because `createClient` sets `codecOptions.useNativeDates`. `NONE`
// fields are optional. Anything crossing a serialisation boundary (SSR, a
// `fetch` response, `JSON.stringify`) goes through `Json<T>`, which maps
// `RecordId<"team">` to `` `team:${string}` `` and `Date` to `string`.
//
// The classes matter beyond reading: a `RecordId` parameter encodes to a
// record link on the wire, while a plain string encodes to a SurrealQL
// string, so `WHERE team = $team` matches only with the class.
//
// This file re-exports the runtime entry points and augments `SurqlRegistry`
// with one entry per analyzed query, keyed by its exact text. Import from here
// — the augmentation loads with them, so no side-effect import is needed.

import type { Decimal, Duration, GeoJSON, RecordId, Uuid } from "@surrealguard/client";

export {
  createClient,
  defineLive,
  defineQuery,
  fromSurreal,
  SurrealGuardError,
} from "@surrealguard/client";
// Value re-exports, so constructing a param needs only this one import:
// `new RecordId("team", "red")`.
export { Decimal, Duration, RecordId, Uuid } from "@surrealguard/client";
export type {
  GeoJSON,
  Json,
  Preloaded,
  SurqlLive,
  SurqlQuery,
  SurrealGuardClient,
} from "@surrealguard/client";

declare module "@surrealguard/client" {
  interface SurqlRegistry {
    "SELECT id, name, age, team FROM person": { result: [Array<{ age: number; id: RecordId<"person">; name: string; team: RecordId<"team"> }>]; params: Record<string, never> };
    "SELECT id, name FROM person WHERE team = $team": { result: [Array<{ id: RecordId<"person">; name: string }>]; params: { team: RecordId<"team"> } };
    "SELECT name FROM person; SELECT age FROM person": { result: [Array<{ name: string }>, Array<{ age: number }>]; params: Record<string, never> };
    "CREATE person SET name = $name, age = $age, team = $team": { result: [Array<{ age: number; id: RecordId<"person">; name: string; team: RecordId<"team"> }>]; params: { age: number; name: string; team: RecordId<"team"> } };
  }
}

// The value types are referenced only when a query result uses them; this keeps
// the imports live regardless.
export type __SurqlGeneratedRefs = [Decimal, Duration, GeoJSON, RecordId, Uuid];
