use std::fmt::Write as FmtWrite;
use std::fs;
use std::path::Path;

use surrealguard_analyzer::context::Context;
use surrealguard_analyzer::schema::extract_schema;
use surrealguard_analyzer::statements::analyze_statement;
use surrealguard_analyzer::types::{Kind, Literal};
use surrealguard_analyzer::{analyze_with_context, parse};
use walkdir::WalkDir;

/// A single query file that has been analyzed.
struct QueryFile {
    /// camelCase function name derived from the file name.
    function_name: String,
    /// The raw SurrealQL source text.
    source: String,
    /// The inferred result type of the query.
    result_type: Kind,
    /// The table name referenced in the query, if any.
    table: Option<String>,
    /// Selected field names (for Pick<> generation), if applicable.
    selected_fields: Vec<String>,
}

/// Scan schema directory, analyze queries, and produce a TypeScript output string.
pub fn generate(schema_dir: &Path, queries_dir: &Path) -> Result<String, String> {
    // 1. Build the schema context from .surql files in the schema directory.
    let mut ctx = Context::new();
    load_schema_dir(schema_dir, &mut ctx)?;

    // 2. Analyze each query file against the schema context.
    let queries = load_query_files(queries_dir, &mut ctx)?;

    // 3. Generate TypeScript output.
    let mut out = String::new();

    writeln!(out, "// Generated by surrealguard-typegen — do not edit").unwrap();
    writeln!(out, "import type {{ Surreal }} from 'surrealdb';").unwrap();
    writeln!(out).unwrap();

    // Schema types
    writeln!(out, "// ── Schema Types ─────────────────────────────────").unwrap();
    writeln!(out).unwrap();
    generate_schema_interfaces(&ctx, &mut out);

    // Query functions
    if !queries.is_empty() {
        writeln!(out, "// ── Query Functions ──────────────────────────────").unwrap();
        writeln!(out).unwrap();
        for query in &queries {
            generate_query_function(query, &ctx, &mut out);
        }
    }

    Ok(out)
}

/// Recursively load all .surql files from a directory and extract schema into context.
fn load_schema_dir(dir: &Path, ctx: &mut Context) -> Result<(), String> {
    if !dir.exists() {
        return Err(format!("schema directory does not exist: {}", dir.display()));
    }

    let mut files: Vec<_> = WalkDir::new(dir)
        .into_iter()
        .filter_map(|e| e.ok())
        .filter(|e| {
            e.path()
                .extension()
                .map(|ext| ext == "surql")
                .unwrap_or(false)
        })
        .collect();

    // Sort for deterministic output.
    files.sort_by(|a, b| a.path().cmp(b.path()));

    for entry in &files {
        let source = fs::read_to_string(entry.path()).map_err(|e| {
            format!(
                "failed to read schema file {}: {}",
                entry.path().display(),
                e
            )
        })?;

        let tree = parse(&source).map_err(|e| {
            format!(
                "failed to parse schema file {}: {}",
                entry.path().display(),
                e
            )
        })?;

        extract_schema(&tree.root_node(), &source, ctx);
    }

    Ok(())
}

/// Load and analyze query .surql files, returning structured results.
fn load_query_files(dir: &Path, ctx: &mut Context) -> Result<Vec<QueryFile>, String> {
    if !dir.exists() {
        return Err(format!(
            "queries directory does not exist: {}",
            dir.display()
        ));
    }

    let mut entries: Vec<_> = WalkDir::new(dir)
        .into_iter()
        .filter_map(|e| e.ok())
        .filter(|e| {
            e.path()
                .extension()
                .map(|ext| ext == "surql")
                .unwrap_or(false)
        })
        .collect();

    entries.sort_by(|a, b| a.path().cmp(b.path()));

    let mut queries = Vec::new();

    for entry in &entries {
        let source = fs::read_to_string(entry.path()).map_err(|e| {
            format!(
                "failed to read query file {}: {}",
                entry.path().display(),
                e
            )
        })?;

        let function_name = file_stem_to_camel_case(entry.path());

        // Clone context for analysis so diagnostics don't leak between queries.
        let mut query_ctx = ctx.clone();
        let _ = analyze_with_context(&source, &mut query_ctx);

        // Determine the result type by re-parsing and analyzing the first statement.
        let tree = parse(&source).map_err(|e| {
            format!(
                "failed to parse query file {}: {}",
                entry.path().display(),
                e
            )
        })?;

        let root = tree.root_node();
        let mut result_type = Kind::Any;
        let mut table: Option<String> = None;
        let mut selected_fields: Vec<String> = Vec::new();

        // Walk to find the first statement and analyze it for its result type.
        let mut cursor = root.walk();
        for child in root.named_children(&mut cursor) {
            let stmt = find_first_statement(&child);
            if let Some(stmt_node) = stmt {
                let mut stmt_ctx = ctx.clone();
                result_type = analyze_statement(&stmt_node, &source, &mut stmt_ctx);

                // Try to extract table and selected fields from the source.
                if let Some(info) = extract_query_info(&stmt_node, &source) {
                    table = Some(info.table);
                    selected_fields = info.fields;
                }
                break;
            }
        }

        queries.push(QueryFile {
            function_name,
            source: source.trim().to_string(),
            result_type,
            table,
            selected_fields,
        });
    }

    Ok(queries)
}

struct QueryInfo {
    table: String,
    fields: Vec<String>,
}

/// Extract table name and selected fields from a statement node.
fn extract_query_info(node: &tree_sitter::Node, source: &str) -> Option<QueryInfo> {
    use surrealguard_analyzer::parser::{child_by_kind, find_all, node_text};

    if node.kind() != "select_statement" {
        // For non-SELECT DML, try to get table name.
        let table = extract_dml_table(node, source)?;
        return Some(QueryInfo {
            table,
            fields: Vec::new(),
        });
    }

    // Extract table from FROM clause.
    let from = child_by_kind(node, "from_clause")?;
    let idents = find_all(&from, "identifier");
    let table = idents
        .first()
        .map(|id| node_text(id, source).to_string())?;

    // Extract selected fields.
    let mut fields = Vec::new();
    let mut cursor = node.walk();
    let mut past_select = false;
    for child in node.children(&mut cursor) {
        let kind = child.kind();
        if kind.starts_with("keyword_select") || kind == "keyword_select" {
            past_select = true;
            continue;
        }
        if kind.starts_with("keyword_from")
            || kind == "keyword_from"
            || kind == "from_clause"
        {
            break;
        }
        if past_select {
            // Check for SELECT *
            if kind == "select_all" || node_text(&child, source).trim() == "*" {
                // SELECT * — no field restriction
                return Some(QueryInfo {
                    table,
                    fields: Vec::new(),
                });
            }
            // Collect identifier names from select_fields / select_clause
            let field_idents = find_all(&child, "identifier");
            for ident in &field_idents {
                let name = node_text(ident, source).to_string();
                if !fields.contains(&name) {
                    fields.push(name);
                }
            }
        }
    }

    Some(QueryInfo { table, fields })
}

/// Extract table name from DML statements (CREATE, UPDATE, DELETE, etc.).
fn extract_dml_table(node: &tree_sitter::Node, source: &str) -> Option<String> {
    use surrealguard_analyzer::parser::{find_all, node_text};

    for wrapper_kind in &[
        "create_target",
        "update_target",
        "delete_target",
        "upsert_target",
    ] {
        let targets = find_all(node, wrapper_kind);
        if let Some(target) = targets.first() {
            let idents = find_all(target, "identifier");
            if let Some(ident) = idents.first() {
                return Some(node_text(ident, source).to_string());
            }
        }
    }
    None
}

/// Find the first statement node by descending through wrapper nodes.
fn find_first_statement<'a>(node: &tree_sitter::Node<'a>) -> Option<tree_sitter::Node<'a>> {
    let kind = node.kind();
    if kind.ends_with("_statement") && kind != "subquery_statement" && kind != "primary_statement" {
        return Some(*node);
    }
    match kind {
        "expressions" | "expression" | "subquery_statement" | "primary_statement" => {
            let mut cursor = node.walk();
            for child in node.named_children(&mut cursor) {
                if let Some(stmt) = find_first_statement(&child) {
                    return Some(stmt);
                }
            }
            None
        }
        _ => None,
    }
}

// ── TypeScript Generation ────────────────────────────────────

/// Generate TypeScript interfaces for all tables in the schema.
fn generate_schema_interfaces(ctx: &Context, out: &mut String) {
    let table_names: Vec<String> = ctx.table_names().map(|s| s.to_string()).collect();

    for table_name in &table_names {
        let interface_name = pascal_case(table_name);
        let fields = ctx.get_fields(table_name);

        writeln!(out, "export interface {} {{", interface_name).unwrap();

        // Always include id field.
        writeln!(out, "  id: string;").unwrap();

        for field in fields {
            // Skip nested fields (contain dots) and id (already added).
            if field.name.contains('.') || field.name == "id" {
                continue;
            }

            let ts_type = match &field.typ {
                Some(kind) => kind_to_ts(kind),
                None => "unknown".to_string(),
            };

            writeln!(out, "  {}: {};", field.name, ts_type).unwrap();
        }

        writeln!(out, "}}").unwrap();
        writeln!(out).unwrap();
    }
}

/// Generate a typed query function for a single query file.
fn generate_query_function(query: &QueryFile, ctx: &Context, out: &mut String) {
    let return_type = compute_return_type(query, ctx);
    let query_source_escaped = query.source.replace('\\', "\\\\").replace('\'', "\\'");

    // Doc comment with the original query.
    writeln!(out, "/** {} */", query.source.replace('\n', " ")).unwrap();

    writeln!(
        out,
        "export async function {}(db: Surreal): Promise<{}> {{",
        query.function_name, return_type
    )
    .unwrap();

    writeln!(
        out,
        "  const [result] = await db.query('{}');",
        query_source_escaped
    )
    .unwrap();

    writeln!(out, "  return result as {};", return_type).unwrap();
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();
}

/// Compute the TypeScript return type for a query.
fn compute_return_type(query: &QueryFile, ctx: &Context) -> String {
    // If we have a table and specific selected fields, generate Pick<>.
    if let Some(ref table) = query.table {
        let interface_name = pascal_case(table);
        // Check if this table exists in the schema.
        let has_table = ctx.get_fields(table).iter().any(|_| true);

        if has_table && !query.selected_fields.is_empty() {
            let field_list = query
                .selected_fields
                .iter()
                .map(|f| format!("'{}'", f))
                .collect::<Vec<_>>()
                .join(" | ");
            return format!("Pick<{}, {}>[]", interface_name, field_list);
        }

        if has_table {
            return format!("{}[]", interface_name);
        }
    }

    // Fall back to converting the analyzed result type.
    let ts = kind_to_ts(&query.result_type);
    // If it's already an array type, return as-is.
    if ts.ends_with("[]") {
        ts
    } else {
        format!("{}[]", ts)
    }
}

/// Convert a SurrealQL `Kind` to a TypeScript type string.
pub fn kind_to_ts(kind: &Kind) -> String {
    match kind {
        Kind::String => "string".to_string(),
        Kind::Int | Kind::Float | Kind::Decimal | Kind::Number => "number".to_string(),
        Kind::Bool => "boolean".to_string(),
        Kind::Datetime => "string".to_string(),
        Kind::Uuid => "string".to_string(),
        Kind::Duration => "string".to_string(),
        Kind::Bytes => "Uint8Array".to_string(),
        Kind::Null => "null".to_string(),
        Kind::Any => "unknown".to_string(),
        Kind::Object => "Record<string, unknown>".to_string(),
        Kind::Array(inner, _) => format!("{}[]", kind_to_ts(inner)),
        Kind::Set(inner, _) => format!("{}[]", kind_to_ts(inner)),
        Kind::Option(inner) => format!("{} | null", kind_to_ts(inner)),
        Kind::Record(tables) => {
            if tables.is_empty() {
                "{ id: string }".to_string()
            } else {
                tables
                    .iter()
                    .map(|t| pascal_case(&t.to_string()))
                    .collect::<Vec<_>>()
                    .join(" | ")
            }
        }
        Kind::Either(variants) => variants
            .iter()
            .map(|v| kind_to_ts(v))
            .collect::<Vec<_>>()
            .join(" | "),
        Kind::Literal(Literal::Object(fields)) => {
            if fields.is_empty() {
                "Record<string, unknown>".to_string()
            } else {
                let entries: Vec<String> = fields
                    .iter()
                    .map(|(k, v)| format!("  {}: {};", k, kind_to_ts(v)))
                    .collect();
                format!("{{\n{}\n}}", entries.join("\n"))
            }
        }
        Kind::Geometry(_) => "GeoJSON".to_string(),
        Kind::Range => "{ begin: unknown; end: unknown }".to_string(),
        _ => "unknown".to_string(),
    }
}

// ── Helpers ──────────────────────────────────────────────────

/// Convert a snake_case string to PascalCase.
///
/// Examples: "user_profile" -> "UserProfile", "user" -> "User"
pub fn pascal_case(s: &str) -> String {
    s.split(|c: char| c == '_' || c == '-')
        .filter(|part| !part.is_empty())
        .map(|part| {
            let mut chars = part.chars();
            match chars.next() {
                Some(first) => {
                    let upper: String = first.to_uppercase().collect();
                    upper + chars.as_str()
                }
                None => String::new(),
            }
        })
        .collect()
}

/// Convert a file stem (e.g., "get_active_users") to camelCase ("getActiveUsers").
fn file_stem_to_camel_case(path: &Path) -> String {
    let stem = path
        .file_stem()
        .unwrap_or_default()
        .to_string_lossy()
        .to_string();

    let parts: Vec<&str> = stem
        .split(|c: char| c == '_' || c == '-')
        .filter(|p| !p.is_empty())
        .collect();

    if parts.is_empty() {
        return "query".to_string();
    }

    let mut result = parts[0].to_lowercase();
    for part in &parts[1..] {
        let mut chars = part.chars();
        if let Some(first) = chars.next() {
            result.extend(first.to_uppercase());
            result.push_str(chars.as_str());
        }
    }

    result
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::collections::BTreeMap;

    #[test]
    fn test_pascal_case() {
        assert_eq!(pascal_case("user"), "User");
        assert_eq!(pascal_case("user_profile"), "UserProfile");
        assert_eq!(pascal_case("my_table_name"), "MyTableName");
        assert_eq!(pascal_case("already"), "Already");
    }

    #[test]
    fn test_file_stem_to_camel_case() {
        assert_eq!(
            file_stem_to_camel_case(Path::new("get_active_users.surql")),
            "getActiveUsers"
        );
        assert_eq!(
            file_stem_to_camel_case(Path::new("list_posts.surql")),
            "listPosts"
        );
        assert_eq!(
            file_stem_to_camel_case(Path::new("simple.surql")),
            "simple"
        );
    }

    #[test]
    fn test_kind_to_ts_primitives() {
        assert_eq!(kind_to_ts(&Kind::String), "string");
        assert_eq!(kind_to_ts(&Kind::Int), "number");
        assert_eq!(kind_to_ts(&Kind::Float), "number");
        assert_eq!(kind_to_ts(&Kind::Bool), "boolean");
        assert_eq!(kind_to_ts(&Kind::Null), "null");
        assert_eq!(kind_to_ts(&Kind::Any), "unknown");
        assert_eq!(kind_to_ts(&Kind::Datetime), "string");
        assert_eq!(kind_to_ts(&Kind::Uuid), "string");
        assert_eq!(kind_to_ts(&Kind::Bytes), "Uint8Array");
    }

    #[test]
    fn test_kind_to_ts_array() {
        let arr = Kind::Array(Box::new(Kind::String), None);
        assert_eq!(kind_to_ts(&arr), "string[]");
    }

    #[test]
    fn test_kind_to_ts_option() {
        let opt = Kind::Option(Box::new(Kind::String));
        assert_eq!(kind_to_ts(&opt), "string | null");
    }

    #[test]
    fn test_kind_to_ts_record_empty() {
        let rec = Kind::Record(vec![]);
        assert_eq!(kind_to_ts(&rec), "{ id: string }");
    }

    #[test]
    fn test_kind_to_ts_object() {
        assert_eq!(kind_to_ts(&Kind::Object), "Record<string, unknown>");
    }

    #[test]
    fn test_kind_to_ts_literal_object() {
        let mut fields = BTreeMap::new();
        fields.insert("name".to_string(), Kind::String);
        fields.insert("age".to_string(), Kind::Int);
        let obj = Kind::Literal(Literal::Object(fields));
        let ts = kind_to_ts(&obj);
        assert!(ts.contains("name: string;"));
        assert!(ts.contains("age: number;"));
    }
}
